name: Android feature CI

on:
  push:
    branches-ignore: [ master, develop ]

env:
  KEY_PATH: ${{ secrets.STORE_FILE }}
  KEY_STORE_PASSWORD: ${{ secrets.STORE_PASS }}
  ALIAS: ${{ secrets.KEY_ALIAS }}
  KEY_PASSWORD: ${{ secrets.KEY_PASS }}

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - run: echo $KEY_PATH

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Unit tests
        run: bash ./gradlew test --stacktrace