name: Android release CI

on:
  push:
    branches: [ master ]

env:
  KEY_PATH: ${{ secrets.STORE_FILE }}
  KEY_STORE_PASSWORD: ${{ secrets.STORE_PASS }}
  ALIAS: ${{ secrets.KEY_ALIAS }}
  KEY_PASSWORD: ${{ secrets.KEY_PASS }}

jobs:

  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Clone Repo
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Unit tests
        run: bash ./gradlew test --stacktrace

  apk:
    name: Generate APK
    runs-on: ubuntu-latest

    steps:
      - name: Clone Repo
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - run: echo $SIGNING_KEY | base64 -d > app/release.keystore
        env:
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}

      - name: Build release APK
        run: bash ./gradlew assembleRelease --stacktrace

      - name: Upload release APK
        uses: actions/upload-artifact@v1
        with:
          name: lego-app-release
          path: app/build/outputs/apk/release/app-release.apk